# Changes here will be overwritten by Copier
_commit: 0.45.0-17-gbd996ed
_src_path: template-nlp
accelerator: cpu
cloud_of_choice: aws
dataset: airline_reviews
deploy_locally: true
deploy_to_huggingface: true
deploy_to_skypilot: true
email: ''
full_name: ZenML GmbH
metric_compare_promotion: true
model: distilbert-base-uncased
notify_on_failures: true
notify_on_successes: false
open_source_license: apache
product_name: nlp_use_case
project_name: ZenML NLP project
sample_rate: false
target_environment: staging
version: 0.0.1
zenml_server_url: ''
