---
name: Fast CI
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
    paths-ignore: [docs/**, docker/**, '*', '!pyproject.toml', '**.md']
  pull_request:
    types: [opened, synchronize, ready_for_review]
    paths-ignore: [docs/**, docker/**, '*', '!pyproject.toml', '**.md']
concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docstring-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-dind-runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'
      - name: Install current package as editable
        run: pip install -U darglint
      - name: Check docstrings
        run: bash scripts/docstring.sh
  sqlite-db-migration-testing:
    runs-on: ubuntu-dind-runners
    # if team member commented, not a draft, on a PR, using /fulltest
    if: github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set up Python 3.9
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.9'
      - name: Test migrations across versions
        run: bash scripts/test-migrations-mysql.sh sqlite
  spellcheck:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Spelling checker
        uses: crate-ci/typos@v1.17.0
        with:
          files: .
          config: ./.typos.toml
  api-docs-test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Set up Python 3.11
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.11'
      - name: Test API docs buildable
        run: bash scripts/generate-docs.sh -v DUMMY -c
  update-templates-to-examples:
    # this doesn't work on forked repositories (i.e. outside contributors)
    # so we disable template updates for those PRs / branches
    if: github.event.pull_request.head.repo.full_name == 'zenml-io/zenml'
    uses: ./.github/workflows/update-templates-to-examples.yml
    with:
      python-version: '3.8'
      os: ubuntu-latest
    secrets: inherit
  custom-ubuntu-setup-and-unit-test:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        os: [ubuntu-dind-runners]
        python-version: ['3.10']
      fail-fast: false
    uses: ./.github/workflows/unit-test.yml
    with:
      python-version: ${{ matrix.python-version }}
      os: ${{ matrix.os }}
    secrets: inherit
  custom-ubuntu-runners-integration-test:
    strategy:
      matrix:
        os: [ubuntu-dind-runners]
        python-version: ['3.10']
        test_environment: [default, docker-server-docker-orchestrator-mysql]
      fail-fast: false
    uses: ./.github/workflows/integration-test-fast.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      test_environment: ${{ matrix.test_environment }}
    secrets: inherit
