---
name: Publish SDK Docs
on:
  push:
    branches: [release/**]
jobs:
  publish:
    name: Build 🔨 and publish 📰 the api docs 📁 to gh-pages
    runs-on: ubuntu-latest
    env:
      ZENML_DEBUG: 1
      ZENML_ANALYTICS_OPT_IN: false
      PYTHONIOENCODING: utf-8
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0  # fetch all commits/branches including gh-pages
      - name: Get the version from the github branch name
        id: get_version
        run: |
          BRANCH='${{github.ref_name}}'
          echo ::set-output name=VERSION::${BRANCH#release/}
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: '14'
      - run: npm install
      - run: npm install html-minifier -g
      - name: Setup environment
        uses: ./.github/actions/setup_environment
        with:
          cache_version: ${{ secrets.GH_ACTIONS_CACHE_KEY }}-api-docs
          python-version: '3.8'
          os: ubuntu-latest
          # We need to install integrations in a different way to avoid conflicts
          install_integrations: 'no'
      - name: Setup git user
        run: |
          git config --global user.name 'Code Monkey'
          git config --global user.email 'codemonkey@zenml.io'
      - name: Runs docs generation
        run: |-
          bash scripts/generate-docs.sh -s src/zenml/ --push --latest -v ${{ steps.get_version.outputs.VERSION }}
