---
name: Scarf checker
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    # Run when md files are involved in the PR.
    paths: ['**.md']
jobs:
  check-for-scarf:
    # Only run on non-draft PRs within the same repository.
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.draft
      == false
    name: check-for-scarf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.1
      - name: Check for scarf
        run: bash scripts/scarf-checker.sh
